os: osx
language: go

go:
  - "1.x"

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/schrej/godacov

script:
  - ./run-tests.sh -ic ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - $GOPATH/bin/godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT

